// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh7lPR5Lul06ocSQQxm-Bn-UqmsOcBkVo',
    appId: '1:839440926513:web:1cc0b21798bc27950d1210',
    messagingSenderId: '839440926513',
    projectId: 'lyallpur-broad-band',
    authDomain: 'lyallpur-broad-band.firebaseapp.com',
    storageBucket: 'lyallpur-broad-band.firebasestorage.app',
    measurementId: 'G-7RWCR8VGRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4z68l4Iek9vC_3YnOE3qk-n1scBiYN_I',
    appId: '1:839440926513:android:6c1c6fd42b6274c60d1210',
    messagingSenderId: '839440926513',
    projectId: 'lyallpur-broad-band',
    storageBucket: 'lyallpur-broad-band.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHDx1pCkrvQaT1BjwsGj8cKjC8ZH-wlCA',
    appId: '1:839440926513:ios:6f44cb1aab4d8a730d1210',
    messagingSenderId: '839440926513',
    projectId: 'lyallpur-broad-band',
    storageBucket: 'lyallpur-broad-band.firebasestorage.app',
    iosBundleId: 'com.example.lyallpurTelecomBroadband',
  );
}
